version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    command: ["python", "/app/backend/analyzer.py"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./media:/app/media
    command: ["npx", "serve", "/app/frontend", "-l", "8080"]

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./backend/vulnerabilities.db:/data/vulnerabilities.db
